//go:build cgo_erigon && cgo_erigon_commitment

package erigon

import (
	"encoding/binary"
	"fmt"
	"path/filepath"

	"github.com/erigontech/mdbx-go/mdbx"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/rlp"
)

// MDBX env geometry — mirrors Erigon's kv_mdbx.go defaults so the
// daemon's compatibility check passes when it later reopens chaindata.
const (
	headerPatchPageSize    = 4096
	headerPatchMapSize     = 4 * 1024 * 1024 * 1024 * 1024
	headerPatchGrowthStep  = 4 * 1024 * 1024 * 1024
	headerPatchMaxDBs uint = 200

	bucketHeaders         = "Header"
	bucketHeaderCanonical = "CanonicalHeader"
)

// patchGenesisHeaderStateRoot rewrites block 0's header.stateRoot in
// the chaindata Headers table. Opens MDBX inline (no shared wrapper);
// closes before returning.
//
// Required because erigon init writes block 0 with whatever root its
// (empty) genesis alloc produced. State-actor's snapshot writer then
// emits all bloat into the snapshot tier — the daemon's first FCU
// recomputes commitment over visible (snapshot) state and rejects the
// erigon-init root. This patch overwrites that root with the
// HPH-over-everything value computed by commitment.ComputeGenesisRoot.
//
// The Headers table is keyed by blockNum(u64-BE) || hash(32); block 0's
// hash is looked up via the CanonicalHeader table.
//
// This is the ONLY state-actor MDBX write besides what `erigon init`
// itself produces — every other state-actor-generated byte lives in the
// snapshot tier (see snapshot_cgo.go).
func patchGenesisHeaderStateRoot(dbPath string, root common.Hash) error {
	chaindataDir := filepath.Join(dbPath, "chaindata")

	env, err := mdbx.NewEnv(mdbx.Label("chaindata"))
	if err != nil {
		return fmt.Errorf("mdbx.NewEnv: %w", err)
	}
	defer env.Close()

	if err := env.SetOption(mdbx.OptMaxDB, uint64(headerPatchMaxDBs)); err != nil {
		return fmt.Errorf("mdbx.SetOption(MaxDB): %w", err)
	}
	if err := env.SetGeometry(-1, -1, headerPatchMapSize, headerPatchGrowthStep, -1, headerPatchPageSize); err != nil {
		return fmt.Errorf("mdbx.SetGeometry: %w", err)
	}
	if err := env.Open(chaindataDir, mdbx.Durable, 0o644); err != nil {
		return fmt.Errorf("mdbx.Open(%s): %w", chaindataDir, err)
	}

	return env.Update(func(txn *mdbx.Txn) error {
		canonicalDBI, err := txn.OpenDBI(bucketHeaderCanonical, 0, nil, nil)
		if err != nil {
			return fmt.Errorf("OpenDBI(%s): %w", bucketHeaderCanonical, err)
		}
		headersDBI, err := txn.OpenDBI(bucketHeaders, 0, nil, nil)
		if err != nil {
			return fmt.Errorf("OpenDBI(%s): %w", bucketHeaders, err)
		}

		blockNumKey := make([]byte, 8)
		binary.BigEndian.PutUint64(blockNumKey, 0)

		hashBytes, err := txn.Get(canonicalDBI, blockNumKey)
		if err != nil {
			return fmt.Errorf("Get(HeaderCanonical, blockNum=0): %w", err)
		}
		if len(hashBytes) != 32 {
			return fmt.Errorf("HeaderCanonical[0] has len=%d, want 32", len(hashBytes))
		}

		headersKey := make([]byte, 0, 8+32)
		headersKey = append(headersKey, blockNumKey...)
		headersKey = append(headersKey, hashBytes...)

		headerRLP, err := txn.Get(headersDBI, headersKey)
		if err != nil {
			return fmt.Errorf("Get(Headers, blockNum=0||hash): %w", err)
		}
		var h types.Header
		if err := rlp.DecodeBytes(headerRLP, &h); err != nil {
			return fmt.Errorf("RLP decode block-0 header: %w", err)
		}
		h.Root = root
		newRLP, err := rlp.EncodeToBytes(&h)
		if err != nil {
			return fmt.Errorf("RLP encode patched block-0 header: %w", err)
		}
		if err := txn.Put(headersDBI, headersKey, newRLP, 0); err != nil {
			return fmt.Errorf("Put(Headers, blockNum=0||hash): %w", err)
		}
		return nil
	})
}
