// Package existence is a pure-Go wrapper around the same bloom-filter
// library Erigon uses for its `.kvei` existence-filter files. The wire
// format must be byte-identical to Erigon's `db/datastruct/existence`
// writer; the `cross-verify-erigon` CI job regenerates fixtures via the
// real Erigon writer and asserts `bytes.Equal`.
//
// # Spec source
//
// Mirrors `db/datastruct/existence/existence_filter.go` from Erigon
// v3.4.2 (see `internal/erigon/constants.go PinnedErigonCommit`). The
// reference file lives at
// `/Users/random_anon/dev/clients/erigon/db/datastruct/existence/existence_filter.go`;
// the lines cited in this package's comments refer to that path.
//
// # Library pin
//
// Erigon imports `github.com/holiman/bloomfilter/v2 v2.0.3` and replaces
// it with `github.com/AskAlexSharov/bloomfilter/v2 v2.0.9` via a
// `replace` directive in its top-level go.mod. State-actor's main
// `go.mod` mirrors that replace verbatim — Go module resolution does
// NOT propagate replace directives from dependencies, so we MUST repeat
// it here for our writer to share the AskAlexSharov fork's wire format.
// If you ever upgrade Erigon and the bloom replace target changes, this
// package WILL emit non-Erigon-readable files; bump the replace in
// state-actor's go.mod to match.
//
// # Wire format
//
// `.kvei` files written by Erigon for non-empty filters use the
// AskAlexSharov fork's `Filter.WriteTo` layout
// (`binarymarshaler.go:MarshallToWriter`):
//
//	bytes 0..11:   header magic "\x00\x00\x00\x00\x00\x00\x00\x00v02\n"
//	bytes 12..35:  k, n, m as 3×uint64 little-endian
//	bytes 36..36+8k:           [k]uint64 random keys (CSPRNG-generated)
//	bytes 36+8k..36+8k+8w:     [(m+63)/64]uint64 bit-array (host-order LE)
//	last 48 bytes:             sha384 of all preceding bytes
//
// `k` is hard-coded to 3 (`bloomfilter.HardCodedK`). `m` is computed
// from the caller's expected key count via
// `bloomfilter.OptimalM(keysCount, 0.01)`.
//
// # Empty filter
//
// When `keysCount < 2` Erigon writes a zero-length `.kvei` file. We do
// the same — `Build()` on an empty builder creates the file with no
// body. The reader-side `OpenFilter` treats any 0-byte file as
// "matches everything" (no false-negative risk).
//
// # Determinism caveat
//
// The bloom filter's k keys are generated by `crypto/rand`, so two
// runs of `NewFilterBuilder` with the same inputs produce DIFFERENT
// bytes. This is by design — Erigon itself is non-deterministic across
// runs at the bloom-keys level. For byte-equality testing the package
// exposes an internal `newWithKeys` test helper that pins the keys;
// production code calls `NewFilterBuilder` and inherits Erigon's
// CSPRNG-keyed behavior.
//
// # AddHash contract
//
// Caller is responsible for pre-salting the input key. The canonical
// pattern (from `db/datastruct/btindex/btree_index.go:436-441`) is:
//
//	hi, _ := murmur3.Sum128WithSeed(key, salt)
//	if err := filter.AddHash(hi); err != nil { ... }
//
// `AddHash` accepts the already-hashed uint64 and feeds it directly
// into `bloomfilter.Filter.AddHash` (no further mixing inside the
// builder). The salt is per-snapshot-version and lives in
// `salt-state.txt` (Part 2's responsibility).
//
// # API
//
//	b, err := existence.NewFilterBuilder(keysCount, "/path/to/foo.kvei", false)
//	for hash := range hashes { _ = b.AddHash(hash) }
//	_ = b.Build()  // writes /path/to/foo.kvei atomically, fsyncs
//
// v1 always passes `useFuse=false`. Passing `useFuse=true` returns
// `ErrFuseFilterUnsupported`; the FuseFilter path is reserved for v2.
//
// # Concurrency
//
// FilterBuilder is single-goroutine; not safe for concurrent AddHash
// or Build calls. The underlying bloomfilter.Filter struct's AddHash
// is also not concurrency-safe (state-actor uses one builder per file).
package existence
