//go:build erigon_gen

// Command erigon-fixture-existence regenerates byte-equality golden
// fixtures for the pure-Go internal/erigon/existence builder by running
// Erigon's reference Filter on a fixed corpus and writing the result to
// a JSON file plus per-fixture .kvei sidecar bytes (recorded as hex in
// the JSON for portability).
//
// Each entry is a (label, keys_count, inputs, bloom_keys, expected_hex)
// quintuple. The bloom keys are extracted from the fixture's own bytes
// (offsets 12..36 are the three uint64 LE keys per
// `binarymarshaler.go:MarshallToWriter`) so the state-actor-side test
// can reconstruct an identical Filter via the unexported
// `newFilterBuilderWithKeys` helper and assert `bytes.Equal`.
//
// Without this trick the fixture would not be reproducible: Erigon
// generates bloom keys via crypto/rand, so two runs of `NewFilter`
// with the same `keysCount` would produce different bytes. Recording
// the keys captures the random choice once per fixture re-gen.
//
// Run:
//
//	cd internal/erigon/_fixtures
//	go run -tags erigon_gen ./cmd/existence \
//	    --out=../../existence/testdata/erigon_golden.json
package main

import (
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"

	"github.com/erigontech/erigon/db/datastruct/existence"
)

// magicLen is the length of the bloom-filter header magic prefix
// ("\x00\x00\x00\x00\x00\x00\x00\x00v02\n") emitted by
// AskAlexSharov/bloomfilter/v2 v2.0.9 at binarymarshaler.go:30. The
// three uint64 LE keys live immediately after the 12-byte magic, the
// 8-byte k, 8-byte n, and 8-byte m fields → starting offset 12+24=36.
const magicLen = 12

// keysOffset is the byte index in a non-empty .kvei file where the
// 3×uint64 random keys begin. magic (12) + k(8) + n(8) + m(8) = 36.
const keysOffset = magicLen + 8*3

type fixture struct {
	Label       string   `json:"label"`
	KeysCount   uint64   `json:"keys_count"`
	Inputs      []uint64 `json:"inputs"`
	BloomKeys   []uint64 `json:"bloom_keys"`
	ExpectedHex string   `json:"expected_hex"`
}

func main() {
	out := flag.String("out", "", "output JSON file path (required)")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "usage: existence --out=<path>")
		os.Exit(2)
	}

	// Curated input shapes. KeysCount governs the bit-array size via
	// bloomfilter.OptimalM(keysCount, 0.01); Inputs are the pre-salted
	// uint64 hashes fed via AddHash.
	corpora := []struct {
		label     string
		keysCount uint64
		inputs    []uint64
	}{
		{"tiny_2", 2, deterministicHashes(2, 0xa1)},
		{"small_10", 10, deterministicHashes(10, 0xb2)},
		{"medium_1000", 1000, deterministicHashes(1000, 0xc3)},
		{"page_boundary_513", 513, deterministicHashes(513, 0xd4)},
		{"empty_one_key", 1, deterministicHashes(1, 0xe5)}, // keysCount<2 → empty file
		{"empty_zero", 0, nil},                             // keysCount=0 → empty file
	}

	tmpRoot, err := os.MkdirTemp("", "existence-fixtures-*")
	if err != nil {
		fmt.Fprintln(os.Stderr, "mkdtemp:", err)
		os.Exit(1)
	}
	defer os.RemoveAll(tmpRoot)

	fixtures := make([]fixture, 0, len(corpora))
	for _, c := range corpora {
		fpath := filepath.Join(tmpRoot, c.label+".kvei")
		filter, err := existence.NewFilter(c.keysCount, fpath, false)
		if err != nil {
			fmt.Fprintf(os.Stderr, "NewFilter(%s): %v\n", c.label, err)
			os.Exit(1)
		}
		filter.DisableFsync() // tmpfs friendliness
		for _, h := range c.inputs {
			if err := filter.AddHash(h); err != nil {
				fmt.Fprintf(os.Stderr, "AddHash(%s, %d): %v\n", c.label, h, err)
				os.Exit(1)
			}
		}
		if err := filter.Build(); err != nil {
			fmt.Fprintf(os.Stderr, "Build(%s): %v\n", c.label, err)
			os.Exit(1)
		}
		raw, err := os.ReadFile(fpath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "ReadFile(%s): %v\n", c.label, err)
			os.Exit(1)
		}
		var keys []uint64
		if len(raw) > 0 {
			if len(raw) < keysOffset+24 {
				fmt.Fprintf(os.Stderr, "%s: file too short for header+keys: %d bytes\n", c.label, len(raw))
				os.Exit(1)
			}
			keys = make([]uint64, 3)
			for i := 0; i < 3; i++ {
				keys[i] = binary.LittleEndian.Uint64(raw[keysOffset+8*i:])
			}
		}
		fixtures = append(fixtures, fixture{
			Label:       c.label,
			KeysCount:   c.keysCount,
			Inputs:      c.inputs,
			BloomKeys:   keys,
			ExpectedHex: hex.EncodeToString(raw),
		})
	}

	data, err := json.MarshalIndent(fixtures, "", "  ")
	if err != nil {
		fmt.Fprintln(os.Stderr, "marshal:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, append(data, '\n'), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Fprintln(os.Stderr, "wrote", *out)
}

// deterministicHashes returns n distinct uint64 values generated by a
// seeded math/rand stream. Using math/rand (not crypto/rand) keeps
// the fixture inputs reproducible across regenerations — the only
// non-determinism in the fixture comes from the bloom filter's own
// CSPRNG-generated keys, which we capture in the fixture record.
func deterministicHashes(n int, seed int64) []uint64 {
	r := rand.New(rand.NewSource(seed))
	out := make([]uint64, n)
	for i := range out {
		out[i] = r.Uint64()
	}
	return out
}
