package oracle

import (
	"testing"

	"github.com/ethereum/go-ethereum/crypto"
)

// TestDepositContractCode_NonEmpty guards against a vendoring regression
// that empties the hex string (would still parse but render the
// canonical-system-contract injection a no-op for one of the five contracts).
func TestDepositContractCode_NonEmpty(t *testing.T) {
	code := DepositContractCode()
	if len(code) == 0 {
		t.Fatal("DepositContractCode returned empty bytes")
	}
	if len(code) < 4096 {
		t.Errorf("DepositContractCode = %d bytes, want >= 4096 (mainnet deposit contract is ~6.5 KB)", len(code))
	}
}

// TestDepositContractCode_HashStable pins the runtime-bytecode keccak256
// against the value computed at vendor time (Prysm v6.0.5-rc.1 /
// protolambda/merge-genesis-tools). A drift here means the const literal
// in deposit_contract.go has changed — re-verify against a trusted source
// (Prysm or a synced mainnet node's eth_getCode reading) before updating
// this expected hash.
//
// The expected hash is generated by running this test once with the
// initial vendored constant and recording the actual value. After that,
// any future drift trips the test.
func TestDepositContractCode_HashStable(t *testing.T) {
	got := crypto.Keccak256Hash(DepositContractCode()).Hex()
	// Pinned to the keccak256 of the Prysm v6.0.5-rc.1 interop
	// constant decoded as bytes. If you intentionally rotate the
	// vendored bytecode (e.g. to match a different solc build, or
	// upgrade to a future Prysm release), update this AND document the
	// new provenance in deposit_contract.go.
	const want = "0x0dd1fffe12df9e127c1e026c772ca1ee307fd69a3f9806ebc75d268090549071"
	if got != want {
		t.Errorf("DepositContractCode keccak256 drifted: got %s, want %s", got, want)
	}
}

// TestDepositContractAddress_PinsMainnet keeps the literal address
// constant in lockstep with go-ethereum/params/config.go's
// MainnetChainConfig.DepositContractAddress (0x00000000219ab540...05Fa).
func TestDepositContractAddress_PinsMainnet(t *testing.T) {
	const want = "0x00000000219ab540356cBB839Cbe05303d7705Fa"
	if got := DepositContractAddress.Hex(); got != want {
		t.Errorf("DepositContractAddress drift: got %s, want %s", got, want)
	}
}
