package reth

import (
	"bytes"

	"github.com/holiman/uint256"
)

// encodeVarUint writes v in LEB128 form (7-bit chunks, MSB continuation).
// Mirrors reth-codecs 0.3.1's varuint encoding for Vec/Option lengths.
func encodeVarUint(buf *bytes.Buffer, v uint64) {
	for v >= 0x80 {
		buf.WriteByte(byte(v) | 0x80)
		v >>= 7
	}
	buf.WriteByte(byte(v))
}

// decodeVarUint reads a LEB128 varuint from b. Returns the decoded value and
// the number of bytes consumed. Panics if b is too short or the encoding
// exceeds 10 bytes (would overflow uint64).
func decodeVarUint(b []byte) (uint64, int) {
	var v uint64
	var shift uint
	for i, c := range b {
		if i >= 10 {
			panic("varuint exceeds 10 bytes")
		}
		v |= uint64(c&0x7f) << shift
		if c&0x80 == 0 {
			return v, i + 1
		}
		shift += 7
	}
	panic("varuint truncated")
}

// encodeU64Compact writes v in big-endian form with leading zero bytes stripped.
// Returns the byte count written. Mirrors reth-codecs 0.3.1's Compact impl
// for u64 (lib.rs:149-183 impl_uint_compact!).
//
// The byte count must be recorded out-of-band (in the parent struct's
// bitflag header for fields; passed to decodeU64Compact by the caller).
func encodeU64Compact(buf *bytes.Buffer, v uint64) int {
	if v == 0 {
		return 0
	}
	var raw [8]byte
	raw[0] = byte(v >> 56)
	raw[1] = byte(v >> 48)
	raw[2] = byte(v >> 40)
	raw[3] = byte(v >> 32)
	raw[4] = byte(v >> 24)
	raw[5] = byte(v >> 16)
	raw[6] = byte(v >> 8)
	raw[7] = byte(v)
	i := 0
	for i < 8 && raw[i] == 0 {
		i++
	}
	n := 8 - i
	buf.Write(raw[i:])
	return n
}

// decodeU64Compact reads a stripped-big-endian u64 of length n bytes from b.
// Length must be 0..=8. Returns the decoded value.
func decodeU64Compact(b []byte, n int) uint64 {
	if n < 0 || n > 8 {
		panic("u64 compact length out of range")
	}
	if n > len(b) {
		panic("u64 compact buffer too short")
	}
	var v uint64
	for i := 0; i < n; i++ {
		v = (v << 8) | uint64(b[i])
	}
	return v
}

// encodeU256Compact writes v in big-endian form with leading zeros stripped.
// Returns byte count written (0..=32). Length is recorded out-of-band like
// encodeU64Compact.
func encodeU256Compact(buf *bytes.Buffer, v *uint256.Int) int {
	var raw [32]byte
	v.WriteToSlice(raw[:])
	i := 0
	for i < 32 && raw[i] == 0 {
		i++
	}
	n := 32 - i
	buf.Write(raw[i:])
	return n
}

// decodeU256Compact reads a stripped-big-endian U256 of length n bytes from b.
func decodeU256Compact(b []byte, n int) *uint256.Int {
	if n < 0 || n > 32 {
		panic("U256 compact length out of range")
	}
	if n > len(b) {
		panic("U256 compact buffer too short")
	}
	var raw [32]byte
	copy(raw[32-n:], b[:n])
	return new(uint256.Int).SetBytes(raw[:])
}

// encodeBytesCompact writes b verbatim. Length is out-of-band; reth-codecs
// stores Bytes-typed fields LAST in struct order so the consumer reads them
// using "remaining buffer length".
func encodeBytesCompact(buf *bytes.Buffer, b []byte) int {
	buf.Write(b)
	return len(b)
}

// decodeBytesCompact returns a copy of the first n bytes of b.
func decodeBytesCompact(b []byte, n int) []byte {
	if n > len(b) {
		panic("bytes compact buffer too short")
	}
	out := make([]byte, n)
	copy(out, b[:n])
	return out
}

// bitflagBuilder accumulates bit fields LSB-first into a header buffer.
// Mirrors the bitflag struct generated by reth-codecs-derive 0.3.1 (lib.rs:29-100).
//
// Order of Put* calls MUST match the field order of the struct being encoded.
type bitflagBuilder struct {
	bits     uint64
	usedBits uint
}

func (b *bitflagBuilder) put(value uint64, width uint) {
	if width > 64 {
		panic("bitflag field exceeds 64 bits")
	}
	if width < 64 && value >= (uint64(1)<<width) {
		panic("bitflag value overflows allocated width")
	}
	b.bits |= value << b.usedBits
	b.usedBits += width
}

func (b *bitflagBuilder) PutBool(v bool) {
	var u uint64
	if v {
		u = 1
	}
	b.put(u, 1)
}

func (b *bitflagBuilder) PutU64Length(n int)  { b.put(uint64(n), 4) }
func (b *bitflagBuilder) PutU128Length(n int) { b.put(uint64(n), 5) }
func (b *bitflagBuilder) PutU256Length(n int) { b.put(uint64(n), 6) }

// Finalize emits the bitflag header as 1 or 2 bytes. totalBits is the sum of
// widths Put* calls used; passed for sanity-check.
func (b *bitflagBuilder) Finalize(totalBits uint) []byte {
	if totalBits != b.usedBits {
		panic("bitflag totalBits mismatch")
	}
	if totalBits == 0 {
		return nil
	}
	if totalBits <= 8 {
		return []byte{byte(b.bits)}
	}
	if totalBits <= 16 {
		return []byte{byte(b.bits), byte(b.bits >> 8)}
	}
	panic("bitflag header > 16 bits not yet supported")
}

// bitflagReader reads bit fields LSB-first.
type bitflagReader struct {
	bits     uint64
	consumed uint
	limit    uint
}

func (r *bitflagReader) Init(header []byte, totalBits uint) {
	r.consumed = 0
	r.limit = totalBits
	r.bits = 0
	for i, c := range header {
		if i >= 8 {
			panic("bitflag header > 8 bytes")
		}
		r.bits |= uint64(c) << (uint(i) * 8)
	}
}

func (r *bitflagReader) get(width uint) uint64 {
	if r.consumed+width > r.limit {
		panic("bitflag read past header")
	}
	mask := (uint64(1) << width) - 1
	v := (r.bits >> r.consumed) & mask
	r.consumed += width
	return v
}

func (r *bitflagReader) GetBool() bool      { return r.get(1) != 0 }
func (r *bitflagReader) GetU64Length() int  { return int(r.get(4)) }
func (r *bitflagReader) GetU128Length() int { return int(r.get(5)) }
func (r *bitflagReader) GetU256Length() int { return int(r.get(6)) }
